### ISSUE TITLE
Refactor Asset Sync to continue after failures

### ISSUE THREAD

**Issue by Eranziel** [ForgeVTT/fvtt-module-forge-vtt#14]
Currently Asset Sync will fail and abort in a few cases, like if a folder fails to be created. Refactor the process to keep a list of failures, skip assets affected by failures, and present the list to the user at completion.

**Comment by rikmarais** [comment]
A user [reported a case](https://discord.com/channels/687213225225355296/694659543052976268/1167234175556919346) where an error in the asset sync can cause the UI to not update properly

![image](https://github.com/ForgeVTT/fvtt-module-forge-vtt/assets/34374883/7bd74fd2-1825-4ad3-bf6d-b156a28dcedc)
![image](https://github.com/ForgeVTT/fvtt-module-forge-vtt/assets/34374883/637a96ae-bdae-4ef8-9a63-7fd1bc3df0c7)

Since this issue deals with a similar case and might be covered, I am making a comment here. It may need a separate issue if it's too far outside the scope, though
